export const pageUrls = {
    HOME: "/",
    NOT_FOUND: "/not-found",
    DASHBOARD: "/dashboard",
    SIGN_IN: "/auth/sign-in",
    SIGN_UP: "/auth/sign-up",
    FORGOT: "/auth/forgot-password",
    FIND_WORKS: "/find-works",
    FIND_JOBS: "/find-jobs",
    JOB_POSTING: "/job-posting",
    JOB_DETAIL: "/jobs/details",
    TALENT: "/talent",
    ORDERS: "/settings/orders",
    CHAT: "/chat",
}